"""Independent literal oracles retained from the specification, before implementation."""
import hashlib
import json
from pathlib import Path
import unittest

from changeset_core import ChangesetError, strict_loads
from changeset_ops import simulate, validate_draft


FIXTURES = Path(__file__).parent / 'tests' / 'fixtures' / 'changesets'
EXPECTED_DIGESTS = {
    'all-json-ops.before.txt': '3695b2ebbfb1713c4e22832daeeaf0dfca9d7476469059ed3ba9ce803000cac9',
    'all-json-ops.changeset.json': 'ad8c43d0f38414faa4ad78176e595420f3065a19b0b25aad402603339d5e0c0a',
    'all-json-ops.expected.txt': 'a3c3eb3b02e6c6947c526c4fe7ef2583ef12e453b1a01caa3a801225da3db724',
    'negative-cases.json': '40bd9468c7baf1edc5123a0a476aa7817ded0a1e09ccd75f767c02442aacbba4',
    'unicode-crlf.before.txt': 'fa9583385f89336ced2a95195c777f0006cc3ad28aa3cb6043bd887c3731e7cc',
    'unicode-crlf.changeset.json': '3d05ca0ecf002d49cd9ce68192e38dfbbb748f66641384dcd5cb2968cbd4c0fe',
    'unicode-crlf.expected.txt': 'a49786992e42fe32d9dd813801561d97e295a3ce51d9a41ba93f98249df3f6e0',
}


class IndependentChangesetTests(unittest.TestCase):
    def fixture(self, name):
        raw = (FIXTURES / name).read_bytes()
        self.assertEqual(hashlib.sha256(raw).hexdigest(), EXPECTED_DIGESTS[name])
        return raw

    def test_exact_specification_json_fixture(self):
        draft = json.loads(self.fixture('all-json-ops.changeset.json'))
        operations = validate_draft(draft, 'report.json')
        actual = simulate('json-ops-v1', self.fixture('all-json-ops.before.txt'),
                          operations, 'json-2space-unicode-lf1')
        self.assertEqual(actual, self.fixture('all-json-ops.expected.txt'))

    def test_exact_specification_crlf_fixture(self):
        draft = json.loads(self.fixture('unicode-crlf.changeset.json'))
        operations = validate_draft(draft, draft['document'])
        actual = simulate('anchored-text-v1', self.fixture('unicode-crlf.before.txt'),
                          operations, None)
        self.assertEqual(actual, self.fixture('unicode-crlf.expected.txt'))

    def test_original_negative_cases_reach_the_intended_boundary(self):
        for case in json.loads(self.fixture('negative-cases.json')):
            with self.subTest(case=case['id']):
                if 'source_json' in case:
                    with self.assertRaises(ChangesetError):
                        strict_loads(case['source_json'].encode())
                    continue
                fmt = case['format']
                # This formats only the synthetic INPUT; expected output is never
                # generated by the implementation under review.
                if fmt == 'json-ops-v1':
                    source = json.dumps(case['source'], indent=2, ensure_ascii=False).encode()
                    renderer = 'json-2space-unicode-lf0'
                else:
                    source = case['source'].encode()
                    renderer = None
                self.assertEqual(simulate(fmt, source, [], renderer), source)
                draft = {'changeset_format': fmt, 'document': 'synthetic.txt',
                         'request_id': 'negative-case', 'operations': [case['operation']]}
                with self.assertRaises(ChangesetError) as caught:
                    ops = validate_draft(draft, 'synthetic.txt')
                    simulate(fmt, source, ops, renderer)
                self.assertNotEqual(caught.exception.code, 'formatting_mismatch')

    def test_missing_required_operation_is_a_bounded_refusal(self):
        draft = {'changeset_format': 'json-ops-v1', 'document': 'synthetic.json',
                 'request_id': 'missing-path', 'operations': [
                     {'id': 'x', 'op': 'set_value', 'old': 1, 'new': 2}]}
        with self.assertRaises(ChangesetError):
            validate_draft(draft, 'synthetic.json')

    def test_direct_simulation_does_not_ignore_execution_fields(self):
        source = b'{\n  "v": 1\n}'
        op = {'id': 'x', 'op': 'set_value', 'path': ['v'], 'old': 1, 'new': 2,
              'shell': 'an inert sentinel that must be rejected'}
        with self.assertRaises(ChangesetError):
            simulate('json-ops-v1', source, [op], 'json-2space-unicode-lf0')


if __name__ == '__main__':
    unittest.main()
